Repository FC-TOY-10/ddock-ple, pull requests merged in 2023-07, with the labels that each got.

#2 [Feat] 통계 화면 UI 작업 및 axios 기본 설정
  package-lock.json
  package.json
  src/apis/axios.ts
  src/apis/index.ts
  src/apis/requests.ts
  src/components/chart/ChartCard.tsx
  src/components/chart/ChartTab.tsx
  src/components/chart/MonthlyChart.tsx
  src/components/chart/WeeklyChart.tsx
  src/components/chart/index.ts
  src/components/common/BottomNav.tsx
  src/components/common/Layout.tsx
  src/components/index.ts
  src/constants/chartCategory.ts
  src/constants/chartTabs.ts
  src/constants/index.ts
  src/pages/App.tsx
  src/pages/Chart.tsx
  src/pages/index.ts
  src/types/ICalendarResponse.ts
  src/types/IRequestByDate.ts
  src/types/IWeeklyHistory.ts
  src/types/index.ts
  src/utils/index.ts
  src/utils/momentUtils.ts
  vite.config.ts
Labels: 완료

#7 [feat] 캘린더 페이지 리스트 삭제 기능 추가
  package-lock.json
  package.json
  src/components/common/BottomNav.tsx
  src/components/monthly/Calendar.tsx
  src/components/monthly/InputModal.tsx
  src/components/monthly/index.ts
  src/pages/App.tsx
  src/pages/Monthly.tsx
  src/pages/index.ts
Labels: 완료

#8 [Feat] 주간 통계 차트 데이터 연동
  src/apis/requests.ts
  src/components/chart/ChartCard.tsx
  src/components/chart/MonthlyChart.tsx
  src/components/chart/WeeklyChart.tsx
  src/types/ISummaryResponse.ts
  src/types/index.ts
  src/utils/momentUtils.ts
Labels: 완료

#18 [Feat] 검색 페이지 작업
  src/apis/requests.ts
  src/components/common/Header.tsx
  src/components/index.ts
  src/components/login/Logout.tsx
  src/components/search/CategoryFilter.tsx
  src/components/search/CategoryFilterModal.tsx
  src/components/search/DateFilterTab.tsx
  src/components/search/SearchResult.tsx
  src/components/search/SearchResultItem.tsx
  src/components/search/index.ts
  src/pages/App.tsx
  src/pages/HomePage.tsx
  src/pages/LoginPage.tsx
  src/pages/Search.tsx
  src/pages/WeeklyPage.tsx
  src/pages/index.ts
  src/types/ISearchQuery.ts
  src/types/index.ts
  src/utils/calcExpend.ts
  src/utils/momentUtils.ts
Labels: 완료

#19 회원가입 + input 컴포넌트 추가 + email 로그인 추가
  src/components/common/Button.tsx
  src/components/common/Input.tsx
  src/components/common/index.ts
  src/components/home/HomeModal.tsx
  src/components/login/AuthGuard.tsx
  src/components/login/Login.tsx
  src/components/login/Logout.tsx
  src/components/login/SignUp.tsx
  src/components/login/index.ts
  src/components/weekly/UpdateModal.tsx
  src/pages/App.tsx
  src/pages/LoginPage.tsx
Labels: 완료

#20 [FIX] 헤더 공통 디자인 수정
  src/GlobalStyle.tsx
  src/components/common/BottomNav.tsx
  src/components/common/Header.tsx
  src/components/common/Layout.tsx
  src/constants/headerLocations.ts
  src/constants/index.ts
  src/pages/App.tsx
Labels: 완료

#30 fix: api path error
  src/apis/requests.ts
Labels: bug

#31 [FIX] Type Error 수정 및 스타일 수정
  netlify.toml
  public/caret-down.svg
  src/apis/index.ts
  src/apis/requests.ts
  src/components/chart/MonthlyTotalCard.tsx
  src/components/home/HomeModal.tsx
  src/components/monthly/InputModal.tsx
  src/components/weekly/DailyExpense.tsx
  src/components/weekly/DeleteModal.tsx
  src/components/weekly/ToggleButton.tsx
  src/components/weekly/UpdateModal.tsx
  src/components/weekly/WeekSummary.tsx
  src/components/weekly/Weekly.tsx
  src/store.ts
Labels: bug, 완료

#32 refactor: 서버 URL 수정
  src/apis/axios.ts
Labels: 완료

#36 [Fix] 공통 스타일 수정 및 회원가입 화면 스타일 수정
  src/components/common/Header.tsx
  src/components/common/Layout.tsx
  src/components/common/Modal.tsx
  src/components/home/Home.tsx
  src/components/login/Login.tsx
  src/components/login/SignUp.tsx
  src/pages/LoginPage.tsx
Labels: bug
